name: Aikido Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  aikido:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node y Aikido CLI
        run: |
          sudo apt update
          sudo apt install -y nodejs npm
          npm install -g @aikidosec/ci-api-client


- name: Ejecutar escaneo
  run: |
    aikido-api-client scan \
      "${{ github.repository }}" \
      "${{ github.event.pull_request.base.sha || github.event.before }}" \
      "${{ github.sha }}" \
      main
