name: Aikido Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  aikido:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Aikido CLI
        run: |
          curl -sSL https://cli.aikido.dev/install.sh -o install.sh
          chmod +x install.sh
          sudo ./install.sh
          which aikido
          aikido --version

      - name: Ejecutar escaneo de Aikido
        run: |
          aikido scan --token ${{ secrets.AIKIDO_TOKEN }}
