name: Aikido Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  aikido:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js y Aikido CI client
        run: |
          sudo apt update
          sudo apt install -y nodejs npm
          npm install -g @aikidosec/ci-api-client

      - name: Configurar token de Aikido
        run: |
          aikido-api-client apikey "${{ secrets.AIKIDO_TOKEN }}"

      - name: Ejecutar escaneo
        run: |
          aikido-api-client scan \
            "${{ github.repository }}" \
            "${{ github.event.pull_request.base.sha || github.event.before }}" \
            "${{ github.sha }}" \
            main
